[package]
name = "gitbrute-rs"
version = "0.1.0"
authors = ["hspug"]
edition = "2018"

[dependencies]
clap = "2"
num_cpus = "1"
rust-crypto = "0.2"
rustc-hex = "2"
scopeguard = "1"

[[bin]]
name = "gitbrute-rs"
path = "main.rs"
